apiVersion: v1
kind: Service
metadata:
  name: notification-controller
  labels:
    control-plane: controller
spec:
  type: ClusterIP
  selector:
    app: notification-controller
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-receiver
  labels:
    control-plane: controller
spec:
  type: ClusterIP
  selector:
    app: notification-controller
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http-webhook
