# permissions for end users to view alerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alert-viewer-role
rules:
- apiGroups:
  - notification.toolkit.fluxcd.io
  resources:
  - alerts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - notification.toolkit.fluxcd.io
  resources:
  - alerts/status
  verbs:
  - get
