# permissions for end users to edit receivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: receiver-editor-role
rules:
- apiGroups:
  - notification.fluxcd.io
  resources:
  - receivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notification.fluxcd.io
  resources:
  - receivers/status
  verbs:
  - get
