# permissions for end users to view receivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: receiver-viewer-role
rules:
- apiGroups:
  - notification.toolkit.fluxcd.io
  resources:
  - receivers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - notification.toolkit.fluxcd.io
  resources:
  - receivers/status
  verbs:
  - get
