apiVersion: notification.fluxcd.io/v1alpha1
kind: Alert
metadata:
  name: alert-sample
spec:
  providerRef:
    name: provider-sample
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
