apiVersion: notification.fluxcd.io/v1alpha1
kind: Alert
metadata:
  name: on-call-webapp
  namespace: gitops-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: webapp
    - kind: Kustomization
      name: webapp-frontend
    - kind: Kustomization
      name: webapp-backend
