name: e2e

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.3.0
      - name: Setup Kustomize
        uses: fluxcd/pkg//actions/kustomize@master
      - name: Setup Kubebuilder
        uses: fluxcd/pkg//actions/kubebuilder@master
      - name: Run tests
        run: make test
        env:
          KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git --no-pager diff
            echo 'run make test and commit changes'
            exit 1
          fi
      - name: Build container image
        run: make docker-build IMG=test/notification-controller:latest
        env:
          KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
      - name: Load test image
        run: kind load docker-image test/notification-controller:latest
      - name: Deploy controller
        run: |
          make dev-deploy IMG=test/notification-controller:latest
          kubectl -n notification-system rollout status deploy/notification-controller --timeout=1m
        env:
          KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
      - name: Run smoke tests
        run: |
          kubectl -n notification-system apply -f ./config/samples
          kubectl -n notification-system wait provider/provider-sample --for=condition=ready --timeout=1m
          kubectl -n notification-system wait alert/alert-sample --for=condition=ready --timeout=1m
          kubectl -n notification-system wait receiver/receiver-sample --for=condition=ready --timeout=1m
      - name: Logs
        run: |
          kubectl -n notification-system logs deploy/notification-controller
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n notification-system get providers -oyaml
          kubectl -n notification-system get alerts -oyaml
          kubectl -n notification-system get receivers -oyaml
          kubectl -n notification-system logs deploy/notification-controller
